In [2]:
#PART A
import torch
scalar = torch.tensor(5)
print(scalar)

vector = torch.tensor([1,2,3])
print(vector)

matrix = torch.tensor([[1,2,3],[4,5,6]])
print(matrix)

tensor_3d = torch.tensor([[[1,2],[3,4]], [[5,6], [7,8]]])
print(tensor_3d)



tensor(5)
tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [3]:
#PART B
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[2, 4], [6, 8]])

add = A + B
print(add)

sub = A - B
print(sub)

mul = A * B
print(mul)

div = A / B
print(div)


tensor([[ 3,  6],
        [ 9, 12]])
tensor([[-1, -2],
        [-3, -4]])
tensor([[ 2,  8],
        [18, 32]])
tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])


In [5]:
#PART C
x = torch.randn(2, 1, 3, 1, 4)

squeezed = torch.squeeze(x)
print(squeezed)

unsqueezed = torch.unsqueeze(x, 0)
print(unsqueezed)

tensor([[[-1.7308,  0.4646, -0.9963,  1.6167],
         [ 1.5086, -1.6008,  1.2966, -1.0962],
         [ 0.4208, -1.3696,  0.0398, -0.7955]],

        [[-1.1885,  0.0235,  0.0132, -0.4092],
         [-0.3828, -0.2557,  0.8587,  1.4567],
         [ 2.0483, -1.0881, -0.6097, -1.0340]]])
tensor([[[[[[-1.7308,  0.4646, -0.9963,  1.6167]],

           [[ 1.5086, -1.6008,  1.2966, -1.0962]],

           [[ 0.4208, -1.3696,  0.0398, -0.7955]]]],



         [[[[-1.1885,  0.0235,  0.0132, -0.4092]],

           [[-0.3828, -0.2557,  0.8587,  1.4567]],

           [[ 2.0483, -1.0881, -0.6097, -1.0340]]]]]])
